obj-y += ../../../services/elevoc_ns/lib/libElevoc_algo_config_v1.4.0_240015.a
obj-y += ../../../services/elevoc_ns/lib/libvocplus_core_TX_DM_24081502.a

ccflags-y := \
		-Iservices/elevoc_ns\
		-Iservices/elevoc_ns/lib\
		-Iservices/elevoc_ns/include\
		-Iservices/elevoc_ns/plugin\
		-Iplatform/hal \
        -Iservices/multimedia/speech/inc \
        -Iutils/heap \
        -Iapps/common\
		-Iapps/factory\
		-Iservices/bt_profiles/inc\
		-Iutils/heap\
		-Iservices/bt_profiles/nc\
		-Iapps/audioplayers\
		-Iservices/bt_app\
		-Iservices/bt_if\
		-Iservices/cp_accel \
		-Iplatform/drivers/cp_accel\
		-Iplatform/drivers/norflash  \
		-Iservices/nv_section/factory_section \
		-Iservices/norflash_api \
		-Iinclude/cmsis_dsp  \
