obj-y := aud_section/ customparam_section/
obj-y += log_section/
obj-y += factory_section/
obj-y += userdata_section/

ifeq ($(TWSPAIRLISTNV),1)
obj-y += fjh_section/
endif

ifeq ($(BLEAPPKEY),1)
obj-y += bleapp_section/
endif